spring:
  application:
    name: ai-code-generate
  profiles:
    active: local

  session:
    store-type: redis
    timeout: 1800 #30分钟过期
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_generate
    username: root
    password: root

  #reids
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      ttl: 3600

server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 1800 #30分钟过期

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.aicodegenerate.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn